// Constants For Reducer Actions
export const PRODUCTS_GET_CATEGORY = "PRODUCTS_GET_CATEGORY";
export const PRODUCTS_GET_PRODUCT = "PRODUCTS_GET_PRODUCT";
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_SUBCATEGORIES_FULFILLED = "FETCH_SUBCATEGORIES_FULFILLED";
export const FETCH_PRODUCTS_FULFILLED = "FETCH_PRODUCTS_FULFILLED";




